import java.util.concurrent.atomic.AtomicLong;
import java.io.PrintStream;
import java.util.Random;
// Generated by Java* Fuzzer test generator (1.0.001). Wed Jan  5 23:24:46 2022
public class Test {

    public static final int N = 400;

    public static long instanceCount=-10L;
    public float fFld=89.320F;
    public static boolean bFld=true;
    public static volatile double dFld=-1.1967;
    public short sFld=-21962;
    public static int iArrFld[]=new int[N];
    public static boolean bArrFld[]=new boolean[N];

    static {
        init(Test.iArrFld, 34974);
        init(Test.bArrFld, false);
    }

    public static long vMeth_check_sum = 0;
    public static long dMeth_check_sum = 0;
    public static long vMeth1_check_sum = 0;

    public static void vMeth1(float f) {

        int i8=-95;

        Test.dFld += 146L;
        i8 += -41196;
        i8 += i8;
        i8 >>= i8;
        i8 >>>= (int)Test.instanceCount;
        i8 = -80;
        Test.instanceCount = Test.instanceCount;
        vMeth1_check_sum += Float.floatToIntBits(f) + i8;
    }

    public double dMeth(double d, int i5) {

        int i6=5514, i7=-94, i9=-14, i10=-12, i11=10;
        double d1=-2.77755, dArr[]=new double[N];
        byte by=-84;
        long lArr1[]=new long[N];
        float fArr[][]=new float[N][N];

        init(lArr1, 6812899197426637662L);
        init(fArr, -2.285F);
        init(dArr, 2.61954);

        i6 = 1;
        do {
            i5 -= (int)Test.instanceCount;
            for (d1 = 1; d1 < 6; ++d1) {
                lArr1[(int)(d1 + 1)] -= Test.instanceCount;
                Test.bFld = (Test.bArrFld[(i6 >>> 1) % N] = Test.bFld);
                vMeth1(fFld);
                d *= i7;
                i5 += (int)(-2.642F + (d1 * d1));
            }
        } while (++i6 < 280);
        for (i9 = 7; 224 > i9; i9 += 2) {
            fArr[i9 - 1][i9 - 1] -= (float)Test.dFld;
        }
        i7 |= i7;
        Test.iArrFld[(i7 >>> 1) % N] = by;
        i11 = 164;
        while (--i11 > 0) {
            Test.dFld = 214233187160359522L;
            dArr[i11 - 1] *= sFld;
        }
        long meth_res = Double.doubleToLongBits(d) + i5 + i6 + Double.doubleToLongBits(d1) + i7 + i9 + i10 + by + i11 +
            checkSum(lArr1) + Double.doubleToLongBits(checkSum(fArr)) +
            Double.doubleToLongBits(checkSum(dArr));
        dMeth_check_sum += meth_res;
        return (double)meth_res;
    }

    public void vMeth(int i3, long l, int i4) {

        long l1=181L, lArr2[]=new long[N];
        int i12=-70, i13=64, i14=-1, i15=-16609;
        byte by1=-66;

        init(lArr2, 5242775699499073777L);

        fFld -= (float)(-((169 * dMeth(Test.dFld, i3)) * i4));
        i4 -= i3;
        for (l1 = 3; l1 < 229; l1++) {
            for (i13 = 1; i13 < 7; ++i13) {
                i4 = i4;
                fFld += (i13 * i13);
                i14 = i4;
                by1 = (byte)l1;
                i15 = 1;
                while (++i15 < 2) {
                    i4 *= -46;
                    lArr2 = lArr2;
                    Test.instanceCount = i15;
                    l >>= i12;
                }
                i14 ^= (int)l;
                i4 += (int)l;
            }
        }
        vMeth_check_sum += i3 + l + i4 + l1 + i12 + i13 + i14 + by1 + i15 + checkSum(lArr2);
    }

    public void mainTest(String[] strArr1) {

        int i=31075, i1=-2, i2=-107, i16=-34934, i17=3, i18=-71, i19=-7, i20=-41098, i21=-13, i22=9;
        byte by2=-43;
        long lArr[]=new long[N];

        init(lArr, 8L);

        for (i = 191; i > 3; --i) {
            i1 = Test.iArrFld[i + 1];
            switch ((i % 9) + 41) {
            case 41:
                i2 = 133;
                do {
                    lArr[i2 - 1] >>>= (i1 >>>= (int)(Test.instanceCount -= (long)(i2 % 95.71801)));
                } while (--i2 > 0);
                vMeth(i1, Test.instanceCount, i1);
                i16 = 133;
                while (--i16 > 0) {
                    i1 *= i1;
                }
                break;
            case 42:
                for (i17 = 3; i17 < 133; i17++) {
                    i1 += (-5 + (i17 * i17));
                    lArr[i + 1] <<= i1;
                }
                break;
            case 43:
            case 44:
                Test.instanceCount -= (long)fFld;
                i1 = -130;
                Test.iArrFld[i] = i18;
                break;
            case 45:
                Test.dFld = i2;
                lArr[i - 1] = Test.instanceCount;
                i1 *= (int)Test.dFld;
                break;
            case 46:
                Test.dFld = i;
                for (i19 = 6; i19 < 133; ++i19) {
                    i20 += (((i19 * by2) + i2) - Test.instanceCount);
                    i20 *= (int)fFld;
                    Test.instanceCount >>= i20;
                    i1 -= (int)fFld;
                    try {
                        i18 = (229 % i2);
                        Test.iArrFld[i] = (i17 % i2);
                        i18 = (Test.iArrFld[i - 1] / i16);
                    } catch (ArithmeticException a_e) {}
                    i18 += i19;
                    i20 = i16;
                    i21 = 1;
                    while (++i21 < 2) {
                        i18 = i;
                        i1 &= -37377;
                        try {
                            i18 = (i20 % i20);
                            i1 = (-2105654224 % Test.iArrFld[i + 1]);
                            i22 = (i2 % 11743);
                        } catch (ArithmeticException a_e) {}
                    }
                }
            case 47:
                fFld = (float)Test.dFld;
                break;
            case 48:
                i22 += i18;
                break;
            case 49:
                Test.iArrFld = Test.iArrFld;
            }
        }

        System.out.println("i i1 i2 = " + i + "," + i1 + "," + i2);
        System.out.println("i16 i17 i18 = " + i16 + "," + i17 + "," + i18);
        System.out.println("i19 i20 by2 = " + i19 + "," + i20 + "," + by2);
        System.out.println("i21 i22 lArr = " + i21 + "," + i22 + "," + checkSum(lArr));

        System.out.println("Test.instanceCount fFld Test.bFld = " + Test.instanceCount + "," +
            Float.floatToIntBits(fFld) + "," + (Test.bFld ? 1 : 0));
        System.out.println("Test.dFld sFld Test.iArrFld = " + Double.doubleToLongBits(Test.dFld) + "," + sFld +
            "," + checkSum(Test.iArrFld));
        System.out.println("Test.bArrFld = " + checkSum(Test.bArrFld));

        System.out.println("vMeth1_check_sum: " + vMeth1_check_sum);
        System.out.println("dMeth_check_sum: " + dMeth_check_sum);
        System.out.println("vMeth_check_sum: " + vMeth_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test _instance = new Test();
                _instance.mainTest(strArr);
         } catch (Exception ex) {
            System.out.println(ex.getClass().getCanonicalName());
         }
    }
    public static PrintStream out = System.out;
    public static Random random = new Random(1);
    public static long seed = 1L;
    public static int UnknownZero = 0;


    public static int nextInt(){
        return random.nextInt();
    }
    public static long nextLong(){
        return random.nextLong();
    }
    public static float nextFloat(){
        return random.nextFloat();
    }
    public static double nextDouble(){
        return random.nextDouble();
    }
    public static boolean nextBoolean(){
        return random.nextBoolean();
    }
    public static byte nextByte(){
        return (byte)random.nextInt();
    }
    public static short nextShort(){
        return (short)random.nextInt();
    }
    public static char nextChar(){
        return (char)random.nextInt();
    }

    public static void init(boolean[] a, boolean seed) {
        for (int j = 0; j < a.length; j++) {
            a[j] = (j % 2 == 0) ? seed : (j % 3 == 0);
        }
    }

    public static void init(boolean[][] a, boolean seed) {
        for (int j = 0; j < a.length; j++) {
            init(a[j], seed);
        }
    }


    public static void init(long[] a, long seed) {
        for (int j = 0; j < a.length; j++) {
            a[j] = (j % 2 == 0) ? seed + j : seed - j;
        }
    }

    public static void init(long[][] a, long seed) {
        for (int j = 0; j < a.length; j++) {
            init(a[j], seed);
        }
    }


    public static void init(int[] a, int seed) {
        for (int j = 0; j < a.length; j++) {
            a[j] = (j % 2 == 0) ? seed + j : seed - j;
        }
    }

    public static void init(int[][] a, int seed) {
        for (int j = 0; j < a.length; j++) {
            init(a[j], seed);
        }
    }


    public static void init(short[] a, short seed) {
        for (int j = 0; j < a.length; j++) {
            a[j] = (short) ((j % 2 == 0) ? seed + j : seed - j);
        }
    }

    public static void init(short[][] a, short seed) {
        for (int j = 0; j < a.length; j++) {
            init(a[j], seed);
        }
    }


    public static void init(char[] a, char seed) {
        for (int j = 0; j < a.length; j++) {
            a[j] = (char) ((j % 2 == 0) ? seed + j : seed - j);
        }
    }

    public static void init(char[][] a, char seed) {
        for (int j = 0; j < a.length; j++) {
            init(a[j], seed);
        }
    }


    public static void init(byte[] a, byte seed) {
        for (int j = 0; j < a.length; j++) {
            a[j] = (byte) ((j % 2 == 0) ? seed + j : seed - j);
        }
    }

    public static void init(byte[][] a, byte seed) {
        for (int j = 0; j < a.length; j++) {
            init(a[j], seed);
        }
    }


    public static void init(double[] a, double seed) {
        for (int j = 0; j < a.length; j++) {
            a[j] = (j % 2 == 0) ? seed + j : seed - j;
        }
    }

    public static void init(double[][] a, double seed) {
        for (int j = 0; j < a.length; j++) {
            init(a[j], seed);
        }
    }


    public static void init(float[] a, float seed) {
        for (int j = 0; j < a.length; j++) {
            a[j] = (j % 2 == 0) ? seed + j : seed - j;
        }
    }

    public static void init(float[][] a, float seed) {
        for (int j = 0; j < a.length; j++) {
            init(a[j], seed);
        }
    }


    public static void init(Object[][] a, Object seed) {
        for (int j = 0; j < a.length; j++) {
            init(a[j], seed);
        }
    }

    public static void init(Object[] a, Object seed) {
        for (int j = 0; j < a.length; j++)
            try {
                a[j] = seed.getClass().newInstance();
            } catch (Exception ex) {
                a[j] = seed;
            }
    }

    public static long checkSum(boolean[] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += (a[j] ? j + 1 : 0);
        }
        return sum;
    }

    public static long checkSum(boolean[][] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += checkSum(a[j]);
        }
        return sum;
    }


    public static long checkSum(long[] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += (a[j] / (j + 1) + a[j] % (j + 1));
        }
        return sum;
    }

    public static long checkSum(long[][] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += checkSum(a[j]);
        }
        return sum;
    }


    public static long checkSum(int[] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += (a[j] / (j + 1) + a[j] % (j + 1));
        }
        return sum;
    }

    public static long checkSum(int[][] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += checkSum(a[j]);
        }
        return sum;
    }


    public static long checkSum(short[] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += (short) (a[j] / (j + 1) + a[j] % (j + 1));
        }
        return sum;
    }

    public static long checkSum(short[][] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += checkSum(a[j]);
        }
        return sum;
    }


    public static long checkSum(char[] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += (char) (a[j] / (j + 1) + a[j] % (j + 1));
        }
        return sum;
    }

    public static long checkSum(char[][] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += checkSum(a[j]);
        }
        return sum;
    }


    public static long checkSum(byte[] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += (byte) (a[j] / (j + 1) + a[j] % (j + 1));
        }
        return sum;
    }

    public static long checkSum(byte[][] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += checkSum(a[j]);
        }
        return sum;
    }


    public static double checkSum(double[] a) {
        double sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += (a[j] / (j + 1) + a[j] % (j + 1));
        }
        return sum;
    }

    public static double checkSum(double[][] a) {
        double sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += checkSum(a[j]);
        }
        return sum;
    }


    public static double checkSum(float[] a) {
        double sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += (a[j] / (j + 1) + a[j] % (j + 1));
        }
        return sum;
    }

    public static double checkSum(float[][] a) {
        double sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += checkSum(a[j]);
        }
        return sum;
    }


    public static long checkSum(Object[][] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += checkSum(a[j]);
        }
        return sum;
    }

    public static long checkSum(Object[] a) {
        long sum = 0;
        for (int j = 0; j < a.length; j++) {
            sum += checkSum(a[j]) * Math.pow(2, j);
        }
        return sum;
    }

    public static long checkSum(Object a) {
        if (a == null)
            return 0L;
        return (long) a.getClass().getCanonicalName().length();
    }


    public static byte[] byte1array(int sz, byte seed) {
        byte[] ret = new byte[sz];
        init(ret, seed);
        return ret;
    }

    public static byte[][] byte2array(int sz, byte seed) {
        byte[][] ret = new byte[sz][sz];
        init(ret, seed);
        return ret;
    }

    public static short[] short1array(int sz, short seed) {
        short[] ret = new short[sz];
        init(ret, seed);
        return ret;
    }

    public static short[][] short2array(int sz, short seed) {
        short[][] ret = new short[sz][sz];
        init(ret, seed);
        return ret;
    }

    public static int[] int1array(int sz, int seed) {
        int[] ret = new int[sz];
        init(ret, seed);
        return ret;
    }

    public static int[][] int2array(int sz, int seed) {
        int[][] ret = new int[sz][sz];
        init(ret, seed);
        return ret;
    }

    public static long[] long1array(int sz, long seed) {
        long[] ret = new long[sz];
        init(ret, seed);
        return ret;
    }

    public static long[][] long2array(int sz, long seed) {
        long[][] ret = new long[sz][sz];
        init(ret, seed);
        return ret;
    }

    public static float[] float1array(int sz, float seed) {
        float[] ret = new float[sz];
        init(ret, seed);
        return ret;
    }

    public static float[][] float2array(int sz, float seed) {
        float[][] ret = new float[sz][sz];
        init(ret, seed);
        return ret;
    }

    public static double[] double1array(int sz, double seed) {
        double[] ret = new double[sz];
        init(ret, seed);
        return ret;
    }

    public static double[][] double2array(int sz, double seed) {
        double[][] ret = new double[sz][sz];
        init(ret, seed);
        return ret;
    }

    public static char[] char1array(int sz, char seed) {
        char[] ret = new char[sz];
        init(ret, seed);
        return ret;
    }

    public static char[][] char2array(int sz, char seed) {
        char[][] ret = new char[sz][sz];
        init(ret, seed);
        return ret;
    }

    public static Object[] Object1array(int sz, Object seed) {
        Object[] ret = new Object[sz];
        init(ret, seed);
        return ret;
    }

    public static Object[][] Object2array(int sz, Object seed) {
        Object[][] ret = new Object[sz][sz];
        init(ret, seed);
        return ret;
    }

    public static boolean[] boolean1array(int sz, boolean seed) {
        boolean[] ret = new boolean[sz];
        init(ret, seed);
        return ret;
    }

    public static boolean[][] boolean2array(int sz, boolean seed) {
        boolean[][] ret = new boolean[sz][sz];
        init(ret, seed);
        return ret;
    }

    public static AtomicLong runningThreads = new AtomicLong(0);

    public static synchronized void runThread(Runnable r) {
        final Thread t = new Thread(r);
        t.start();
        runningThreads.incrementAndGet();
        Thread t1 = new Thread(new Runnable() {
            public void run() {
                try {
                    t.join();
                    runningThreads.decrementAndGet();
                } catch (InterruptedException e) {
                }
            }
        });
        t1.start();
    }

    public static void joinThreads() {
        while (runningThreads.get() > 0) {
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }
}
///////////////////////////////////////////////////////////////////////
//DEBUG  Test ->  Test
//DEBUG  main ->  main
//DEBUG  mainTest ->  mainTest
//DEBUG  vMeth ->  vMeth mainTest
//DEBUG  dMeth ->  dMeth vMeth mainTest
//DEBUG  vMeth1 ->  vMeth1 dMeth vMeth mainTest
//DEBUG  Depth = 3
//DEBUG  Classes = 1
//DEBUG  static objects = {}
