// Generated by Java* Fuzzer test generator (1.0.001). Thu Jan  6 01:05:45 2022
public class Test {

    public static final int N = 400;

    public static long instanceCount=227L;
    public static int iFld=-5;
    public static volatile double dArrFld[]=new double[N];
    public static int iArrFld[]=new int[N];

    static {
        FuzzerUtils.init(Test.dArrFld, -35.38200);
        FuzzerUtils.init(Test.iArrFld, 13);
    }

    public static long vMeth_check_sum = 0;
    public static long vMeth1_check_sum = 0;
    public static long vMeth2_check_sum = 0;

    public static void vMeth2(int i2) {

        int i3=167, i4=-56, i5=117, i6=-13, iArr1[]=new int[N];
        float f1=0.605F;
        double d=-118.46446;
        boolean b=false, bArr[]=new boolean[N];
        long lArr[]=new long[N];

        FuzzerUtils.init(lArr, 30838L);
        FuzzerUtils.init(bArr, false);
        FuzzerUtils.init(iArr1, -36499);

        lArr[(-29475 >>> 1) % N] /= (Test.instanceCount | 1);
        i2 = i2;
        if (b) {
            for (i3 = 11; i3 < 378; ++i3) {
                f1 += i2;
                bArr = bArr;
                for (i5 = 1; i5 < 5; ++i5) {
                    switch (((i3 % 5) * 5) + 90) {
                    case 92:
                        try {
                            i4 = (i3 / 212);
                            iArr1[i3] = (i5 % -105);
                            i4 = (i4 % -167);
                        } catch (ArithmeticException a_e) {}
                        d = Test.instanceCount;
                    case 94:
                        i2 += (i5 | (long)f1);
                        Test.instanceCount += (long)f1;
                        i4 = 99;
                        break;
                    case 106:
                        i2 ^= (int)-41834L;
                        break;
                    case 95:
                        iArr1[i3 + 1] = i3;
                        break;
                    case 98:
                        i6 += i6;
                        break;
                    }
                }
            }
        } else {
            iArr1[(215 >>> 1) % N] += i3;
        }
        vMeth2_check_sum += i2 + i3 + i4 + Float.floatToIntBits(f1) + i5 + i6 + Double.doubleToLongBits(d) + (b ? 1 :
            0) + FuzzerUtils.checkSum(lArr) + FuzzerUtils.checkSum(bArr) + FuzzerUtils.checkSum(iArr1);
    }

    public static void vMeth1(int i, int i1) {

        float f=-36.656F, f2=101.41F;
        int i7=-101, i8=-192, i9=-13, i10=14, iArr[][][]=new int[N][N][N];
        double d1=96.125212;

        FuzzerUtils.init(iArr, 101);

        i1 = i1;
        f += (++i1);
        iArr[(i >>> 1) % N][(i >>> 1) % N][(i1 >>> 1) % N] += i;
        vMeth2(i);
        i7 = 1;
        do {
            for (i8 = 4; i8 > 1; i8--) {
                d1 = d1;
                for (f2 = 1; f2 < 2; f2++) {
                    if (false) break;
                    i9 = i1;
                    i1 += 144;
                    i10 -= (int)f;
                    iArr[(int)(f2 - 1)][(int)(f2)][i8] = i10;
                    i1 <<= -29190;
                    Test.dArrFld = Test.dArrFld;
                }
            }
        } while (++i7 < 390);
        vMeth1_check_sum += i + i1 + Float.floatToIntBits(f) + i7 + i8 + i9 + Double.doubleToLongBits(d1) +
            Float.floatToIntBits(f2) + i10 + FuzzerUtils.checkSum(iArr);
    }

    public static void vMeth(byte by) {

        int i11=94, i12=-189, i13=-2, i14=180, i15=-54063, i16=129, i17=11797, iArr2[]=new int[N];
        boolean b1=false;
        double d2=-1.43336;
        short s=-12824;

        FuzzerUtils.init(iArr2, -22459);

        vMeth1(i11, i11);
        for (i12 = 2; 209 > i12; ++i12) {
            if (b1) break;
            Test.instanceCount += Test.instanceCount;
        }
        d2 = s;
        for (i14 = 6; 330 > i14; i14++) {
            i11 *= i13;
            for (i16 = 1; 5 > i16; ++i16) {
                i17 += (i16 - i13);
                iArr2[i14] |= i14;
                try {
                    i15 = (i14 % 240);
                    i15 = (Test.iFld % -255);
                    iArr2[i16 + 1] = (i17 % 204);
                } catch (ArithmeticException a_e) {}
                Test.instanceCount <<= by;
                Test.instanceCount -= -224;
                Test.iFld |= i15;
                Test.iFld *= s;
            }
        }
        vMeth_check_sum += by + i11 + i12 + i13 + (b1 ? 1 : 0) + Double.doubleToLongBits(d2) + s + i14 + i15 + i16 +
            i17 + FuzzerUtils.checkSum(iArr2);
    }

    public void mainTest(String[] strArr1) {

        byte by1=-26, byArr[]=new byte[N];
        int i19=7, i20=35, i21=12, i22=9, i23=-48, i24=43;
        double d3=-20.108593;
        float f3=-35.744F;
        boolean bArr1[]=new boolean[N];

        FuzzerUtils.init(bArr1, true);
        FuzzerUtils.init(byArr, (byte)-126);

        vMeth(by1);
        for (int i18 : Test.iArrFld) {
            Test.instanceCount = i18;
            Test.iArrFld[(i19 >>> 1) % N] -= Test.iFld;
            Test.iFld -= (int)d3;
            f3 -= i18;
            switch ((((i19 >>> 1) % 2) * 5) + 30) {
            case 32:
                i20 = 1;
                do {
                    Test.instanceCount = i20;
                    Test.dArrFld[i20 + 1] *= i20;
                    i18 /= (int)(Test.iFld | 1);
                    i19 = (int)Test.instanceCount;
                    f3 = -57071;
                    Test.iFld += (int)1.28266;
                    for (i21 = 1; i21 > i20; i21--) {
                        boolean b2=false;
                        try {
                            i18 = (54627 / i22);
                            Test.iFld = (Test.iArrFld[i21 + 1] % Test.iFld);
                            Test.iArrFld[i21 + 1] = (143 / i21);
                        } catch (ArithmeticException a_e) {}
                        bArr1[i20 + 1] = b2;
                    }
                    i22 >>>= i21;
                    f3 -= 6;
                } while (++i20 < 63);
                Test.instanceCount -= Test.instanceCount;
                f3 = i19;
                for (i23 = 3; i23 < 63; i23 += 3) {
                    short s1=31371;
                    Test.iArrFld[i23 + 1] -= i20;
                    i19 ^= i22;
                    switch ((i23 % 3) + 33) {
                    case 33:
                        i18 = i24;
                        break;
                    case 34:
                        Test.instanceCount = i21;
                        byArr[i23] >>>= (byte)i19;
                        i22 *= -55945;
                        i19 -= (int)d3;
                    case 35:
                        Test.iArrFld[i23 - 1] >>>= s1;
                        break;
                    default:
                        i24 += i23;
                    }
                }
                break;
            case 40:
                i24 -= (int)-111.852F;
            default:
                d3 = i23;
            }
        }

        FuzzerUtils.out.println("by1 i19 d3 = " + by1 + "," + i19 + "," + Double.doubleToLongBits(d3));
        FuzzerUtils.out.println("f3 i20 i21 = " + Float.floatToIntBits(f3) + "," + i20 + "," + i21);
        FuzzerUtils.out.println("i22 i23 i24 = " + i22 + "," + i23 + "," + i24);
        FuzzerUtils.out.println("bArr1 byArr = " + FuzzerUtils.checkSum(bArr1) + "," + FuzzerUtils.checkSum(byArr));

        FuzzerUtils.out.println("Test.instanceCount Test.iFld Test.dArrFld = " + Test.instanceCount + "," + Test.iFld +
            "," + Double.doubleToLongBits(FuzzerUtils.checkSum(Test.dArrFld)));
        FuzzerUtils.out.println("Test.iArrFld = " + FuzzerUtils.checkSum(Test.iArrFld));

        FuzzerUtils.out.println("vMeth2_check_sum: " + vMeth2_check_sum);
        FuzzerUtils.out.println("vMeth1_check_sum: " + vMeth1_check_sum);
        FuzzerUtils.out.println("vMeth_check_sum: " + vMeth_check_sum);
    }
    public static void main(String[] strArr) {

        try {
            Test _instance = new Test();
            for (int i = 0; i < 10; i++ ) {
                _instance.mainTest(strArr);
            }
         } catch (Exception ex) {
            FuzzerUtils.out.println(ex.getClass().getCanonicalName());
         }
    }
}
///////////////////////////////////////////////////////////////////////
//DEBUG  Test ->  Test
//DEBUG  main ->  main
//DEBUG  mainTest ->  mainTest
//DEBUG  vMeth ->  vMeth mainTest
//DEBUG  vMeth1 ->  vMeth1 vMeth mainTest
//DEBUG  vMeth2 ->  vMeth2 vMeth1 vMeth mainTest
//DEBUG  Depth = 3
//DEBUG  Classes = 1
//DEBUG  static objects = {}
